name: Integration Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.13', '3.11.5' ]

    env:
      POETRY_NO_INTERACTION: 1
      PIP_DEFAULT_TIMEOUT: 100  

    steps:
      - name: Set up Python & Poetry
        uses: EM51641/csi/.github/actions/build_pyvalidator@main
        with:
          poetry_version: '1.6.1'
          python_version: ${{ matrix.python-version }}

      - name: Execute Pytest
        run: poetry run python -m pytest --cov=pycsi tests/integration